server:
   port: 8080

spring:
    jpa:
      database-platform: es.symbioserver.sqlite.SQLiteDialect
      show-sql: true
      
      hibernate:
        ddl-auto: create
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        
security:
    oauth2:
      resource:
            id: oauth2_id